services:
  - type: web
    name: save-restricted-content-bot
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_DB
        sync: false
      - key: OWNER_ID
        sync: false
      - key: FORCE_SUB
        value: "0"
      - key: LOG_GROUP
        value: "0"
      - key: STRING
        sync: false
      - key: DB_NAME
        value: telegram_downloader
      - key: MASTER_KEY
        sync: false
      - key: IV_KEY
        sync: false
      - key: YT_COOKIES
        sync: false
      - key: INSTA_COOKIES
        sync: false
      - key: FREEMIUM_LIMIT
        value: "0"
      - key: PREMIUM_LIMIT
        value: "500"
      - key: JOIN_LINK
        value: https://t.me/team_4hl
      - key: ADMIN_CONTACT
        sync: false
